# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Toronto Scala
tagline:          'Functional'
description:      'Toronto Scala Functional'
url:              http://scalator.ca
baseurl:          /

author:
  name:           'Sean Glover and Katrin Shechtman'
  url:            https://twitter.com/torontoscala

paginate:         20

# Custom vars
version:          0.1.0

github:
  repo:           https://github.com/scalator/scalator.github.io
