# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            scalator
tagline:          'scalator'
description: >
  Toronto's Scala Meetup
url:              http://scalator.ca
baseurl:          ''

author:
  name:           'Sean Glover and Katrin Shechtman'
  url:            https://twitter.com/torontoscala
  github:         scalator
  twitter:        scalato
  meetup:         scalator

paginate:         20

# Custom vars
version:          0.1.0

github:
  repo:           https://github.com/scalator/scalator.github.io

google_analytics: 'UA-69070925-1'